### PR TITLE
Drop all control flow entries from estack after fork

### PR DESCRIPTION
**Pull request by xyb3rt**
Fixes issue #68.

### CODE REVIEW

**Comment by xyb3rt** [comment]
Is this ok with you, @rakitzis?

**Comment by rakitzis** [comment]
This may indeed be an oversight. It may be easy to test the `backq` use case since `setsigdefaults` clears `sigexit`, so there is a deterministic way to provoke bad behavior.

**Comment by rakitzis** [comment]
So it's really not obvious, but I traced this down.. may be worth documenting in backq after calling fork(): since the backquoted command is invoked by exec(), and since exec() calls setsigdefaults, restoring signals is not needed in the setup after fork().

**Comment by rakitzis** [comment]
It also seems like setsigdefaults is called redundantly in many cases. In fact, perhaps in all the cases excluding backq!

The logic here is quite twisted. I can't say I'm proud of it 30 years on. I would leave it alone, as a real fix may involve keeping track of some sort of state which needs to be applied after fork() and before exec(). Doing this via a collection of booleans sprinkled through the code is very brittle.

**Pull request merged**
