### PR TITLE
Update dead link in man page

### PR DESCRIPTION
**Pull request by MaxGyver83**
Replace dead link to Duff's paper in man page with link to archived page.

### CODE REVIEW

**Comment by avindra** [comment]
Alternatively, can use this link:

**Comment by MaxGyver83** [comment]
> Alternatively, can use this link:
> 
> https://doc.cat-v.org/plan_9/2nd_edition/papers/rc/

For me, any working link is good!

**Comment by rakitzis** [comment]
Let's go with the cat-v source. Can you update your PR? I will merge. I don't know the copyright status of this paper. I could look into making this a downloadable resource in the repo itself, but I don't know who is responsible for this paper now. Any ideas?

**Comment by MaxGyver83** [comment]
I have changed the link.

No idea about the copyright of the paper.

**Pull request merged**
